#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Vignesh M Rajendran

# Short bio or description (displayed in the header)
description: Crisis Financial Management Scientist with focus on resource constrained environments for SMEs

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Vignesh's homepage
